### ISSUE TITLE
Reply 'non admin human'

### ISSUE THREAD

**Issue by 7DSMeliodas** [GauthamramRavichandran/MasterBot#12]
The Text 

Hello there, non-admin Human!
    I'm the MasterBot. I help admin in managing bots/programs running in your server.

What can I do?
    1. I pull the latest update of a repo to server and restart that appropriate bot.
    2. Monitor the server statistics
    3. Notify you about the failed/stopped bots

Shouldn't appear on service messages.

You should just ignore 'service messages'

**Comment by GauthamramRavichandran** [comment]
fixed in latest commit
